[tool.cibuildwheel]
build-verbosity = 1
archs = ["all"]
# Use the manylinux_2_28 images for the Linux wheels.
manylinux-x86_64-image = "manylinux_2_28"
manylinux-i686-image = "manylinux_2_28"
environment = { SKLEARN_SKIP_NETWORK_TESTS = "1" }
before-build = "bash {project}/tools/cibw_before_build.sh {project}"
before-test = "pip install -r {project}/requirements/test_requirements.txt"
test-command = "bash {project}/tools/test_wheels.sh {project}"

[tool.cibuildwheel.windows]
# Needed on Windows CI to compile with Visual Studio compiler
# otherwise Meson detects a MINGW64 platform and use MINGW64
# toolchain
config-settings = "setup-args=--vsenv"
repair-wheel-command = "bash tools/repair_windows_wheels.sh {wheel} {dest_dir}"
# On Windows, we use a custom Docker image and the test dependencies are
# installed inside the Docker image rather than on the host, so there are no
# test requirements to install here.
test-requires = []
